services:
  - type: web
    name: __LABEL__-companion
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: PORT
        value: "10000"
