name: CI
on: [push, pull_request]
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - name: Install deps
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt ( pip install -r requirements.txt )
          pip install pytest requests python-dotenv
      - name: Run tests (server auto-start by tests)
        env:
        START_LOCAL: "1"
        START_CMD: "python server.py"
        BASE_URL: "http://127.0.0.1:5000"
        PORT: "5000"
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        INTERNAL_TOKEN: ${{ secrets.INTERNAL_TOKEN }}

        run: pytest -q -s
