name: CI

on:
  push:
  pull_request:

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install deps
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt (
            pip install -r requirements.txt
          )
          pip install pytest requests python-dotenv

      - name: Start server (background)
        shell: cmd
        run: |
          REM Démarre app.py en arrière-plan
          start /B "" python app.py
          REM Attendre /health (30s)
          powershell -Command ^
            "$u = 'http://127.0.0.1:5000/health';" ^
            "$ok = $false; $deadline = (Get-Date).AddSeconds(30);" ^
            "while((Get-Date) -lt $deadline) { try { $r = Invoke-WebRequest -Uri $u -UseBasicParsing -TimeoutSec 3; if ($r.StatusCode -eq 200) { $ok = $true; break } } catch {} Start-Sleep -Milliseconds 500 };" ^
            "if (-not $ok) { Write-Error 'Server not responding on /health' }"

      - name: Run tests
        env:
          BASE_URL: http://127.0.0.1:5000
          START_LOCAL: "0"   # CI démarre déjà le serveur
          # Facultatif: configure dans Settings > Secrets and variables > Actions
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          INTERNAL_TOKEN: ${{ secrets.INTERNAL_TOKEN }}
        run: pytest -q
